### ISSUE TITLE
Stereo QuadBuffer Rendering is not working

### ISSUE THREAD

**Issue by koosha94** [uic-evl/omegalib#117]
Currently omegalib does not support quad bufer rendering in its config and config generator.
Moreover in my personal experience even playing with equalizer config generated by omegalib config generator won't help and it wether resault in no window or just normal double buffer window setup.

PS+ I have not used this version of equalizer used in Omegalib, so my Equalizer configuration could be wrong.

Equalizer Configuration file for a 5 Wall cave. that uses 5 nodes( 1 pipe per node, 1 wall per pipe).
https://gist.github.com/koosha94/2ec97eab19b085250625

**Comment by febret** [comment]
:+1:
