### ISSUE TITLE
omegalib does not build from git (Ubuntu 14.04)

### ISSUE THREAD

**Issue by jonathankhoo** [uic-evl/omegalib#141]
$ date
Tue Feb 24 11:01:37 AEDT 2015

All listed dependencies on the readme are already installed:

$ sudo apt-get install freeglut3 freeglut3-dev python-dev flex bison
[sudo] password for jonathan: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
bison is already the newest version.
flex is already the newest version.
freeglut3 is already the newest version.
freeglut3-dev is already the newest version.
python-dev is already the newest version.
The following package was automatically installed and is no longer required:
  linux-image-generic
Use 'apt-get autoremove' to remove it.
0 to upgrade, 0 to newly install, 0 to remove and 12 not to upgrade.

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

$ pwd
/home/jonathan/git/omegalib.git

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

$ mkdir build
$ ccmake ../
(changed prefix to local folder)

$ make -j8

/home/jonathan/git/omegalib.git/src/omega/Camera.cpp: In member function ‘virtual void omega::Camera::handleEvent(const omicron::Event&)’:
/home/jonathan/git/omegalib.git/src/omega/Camera.cpp:147:43: warning: comparison between ‘enum omicron::Service::ServiceType’ and ‘enum omicron::EventBase::ServiceType’ [-Wenum-compare]
         if(evt.getServiceType() == Event::ServiceTypeMocap &&
                                           ^
/home/jonathan/git/omegalib.git/src/omega/Camera.cpp:148:44: error: ‘const class omicron::Event’ has no member named ‘getUserId’
             ((myTrackerUserId != -1 && evt.getUserId() == myTrackerUserId) ||
                                            ^
make[2]: *** [src/omega/CMakeFiles/omega.dir/DisplayConfig.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/omega/CMakeFiles/omega.dir/DisplayTileConfig.cpp.o] Error 1
make[2]: *** [src/omega/CMakeFiles/omega.dir/DrawContext.cpp.o] Error 1
make[2]: *** [src/omega/CMakeFiles/omega.dir/Camera.cpp.o] Error 1
make[1]: *** [src/omega/CMakeFiles/omega.dir/all] Error 2
make: *** [all] Error 2

$ make
[  2%] Built target omicron
[ 62%] Built target FreeImage
[ 69%] Built target freetype
[ 75%] Built target ftgl
[ 75%] Built target glew
[ 76%] Built target equalizer
[ 76%] Building CXX object src/omega/CMakeFiles/omega.dir/Camera.cpp.o
/home/jonathan/git/omegalib.git/src/omega/Camera.cpp: In member function ‘virtual void omega::Camera::handleEvent(const omicron::Event&)’:
/home/jonathan/git/omegalib.git/src/omega/Camera.cpp:147:43: warning: comparison between ‘enum omicron::Service::ServiceType’ and ‘enum omicron::EventBase::ServiceType’ [-Wenum-compare]
         if(evt.getServiceType() == Event::ServiceTypeMocap &&
                                           ^
/home/jonathan/git/omegalib.git/src/omega/Camera.cpp:148:44: error: ‘const class omicron::Event’ has no member named ‘getUserId’
             ((myTrackerUserId != -1 && evt.getUserId() == myTrackerUserId) ||
                                            ^
make[2]: *** [src/omega/CMakeFiles/omega.dir/Camera.cpp.o] Error 1
make[1]: *** [src/omega/CMakeFiles/omega.dir/all] Error 2
make: *** [all] Error 2

Have I done anything (obviously) wrong?

**Comment by febret** [comment]
Hi Jonhatan,
it looks like your omicron submodule is out of date: try going to your omegalib.git dir and do
```
git submodule update omicron
```

**Comment by jonathankhoo** [comment]
Thanks - a bit of   progress.

```
$ make
[  2%] Built target omicron
[ 62%] Built target FreeImage
[ 69%] Built target freetype
[ 75%] Built target ftgl
[ 75%] Built target glew
[ 76%] Built target equalizer
[ 92%] Built target omega
Linking CXX executable ../../bin/ohello
../../bin/libomega.so: undefined reference to `omicron::DataManager::cleanup()'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/ohello] Error 1
make[1]: *** [examples/ohello/CMakeFiles/ohello.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by febret** [comment]
Try
```
> make -B omicron
> make
```
The first line will force a rebuild of omicron ~ make seems to forget to do it after you update the submodule.

**Comment by jonathankhoo** [comment]
Perfect! Built successfully now - thanks for the information and help.

**Comment by febret** [comment]
Glad it worked! Let me know if you need additional help in the future.
Some help may also be found here: https://groups.google.com/forum/#!forum/omegalib
