### ISSUE TITLE
Support for Floor and Ceiling Displays

### ISSUE THREAD

**Issue by bk5115545** [uic-evl/omegalib#160]
Currently when we try to use omegalib on our CAVE system, we see very distorted images on our floor.  I suspect that we would see the same thing on the ceiling.

Is there a method of supporting floor and ceiling displays that form right angles at corners?  
I see an option for custom configurations but it appears that the yaw parameter is not passed around correctly since the floor camera is still at the same angle as the back wall (i.e vertical).

**Comment by febret** [comment]
This is definitely a bug in the configuration builder. I also realize in your case it might be more practical to enter the position of the tile corners directly instead of entering center+pitch+roll...

I can put it a patch for you in the next 2/3 days ~ are you building from the master or release branch?

**Comment by bk5115545** [comment]
I believe we're building from the master branch.

Thanks for the very quick diagnosis and reply.

**Comment by febret** [comment]
FYI the fix goes here if you want to take a quick stab at it:
https://github.com/uic-evl/omegalib/blob/master/src/omega/DisplayTileConfig.cpp#L134

BTW: I think you want to change the pitch, not the yaw for the ground

**Comment by bk5115545** [comment]
Thanks.  We'll look at it as well.

**Comment by bk5115545** [comment]
Alright.  We can't seem to get Omegalib to generate a valid equalizer config.  
If it won't take you too long, can you get a patch sometime soon?

**Comment by febret** [comment]
Sure, I can put in a fix for you. Can you post your current configuration file & the .eqcfg.eqc file in your bin directory?

**Comment by bk5115545** [comment]
Below is our full omegalib config.  I can't attach the file because I don't have write permission to this repository.  Also, I was asked to anonymize our internal IP address space.  There doesn't seem to be a .eqcfg.eqc file in our bin or any file matching "*.eqc" anywhere but in the equalizer-prefix folder.

config:
	display: {
		// We use a custom configuration - we want to specify each tile position and orientation
		type = "Equalizer";
		geometry = "ConfigPlanar";

		// Trying to set a reference tile results in a distorted image
		referenceTile = [0, 0];
		referenceOffset = [-0.5, 2.0, -2.0];

		tileSize = [1.7399, 1.5494];
		tileResolution = [2160, 1920];
		stereoMode = "Interleaved";
		enableStencilInterleaver = true;
		borderless = true;

		tiles: {
			local: {
				// Operator window
				operator: 			{
					device = 0; // Run on GPU 0
					center = [ 0, 2, -2];
					yaw = 0;
					// Offset applied to mouse coordinates
					offset = [0, 0];
					// Window position
					position = [0, 0];
					// Tile resolution
					resolution = [854, 480];
					// Tile size in meters
					size = [2.0, 1.12];
					enabled = true;
				};
			};


			// Left Top
			node1: {
				hostname = "ip.add.res.s01";
				port = 2000;
				left-topleft: {
					device = 0;
					center = [ -1.7399, 2.3241, 0.86995];
					yaw = -90;
					offset = [0, 320];
					position = [0, 0];
					enabled = true;
					disableMouse = true;
				};
				left-topright: {
					device = 1;
					center = [ -1.7399, 2.3241, -0.86995];
					yaw = -90;
					offset = [0, 320];
					position = [2160, 0];
					enabled = true;
					disableMouse = true;
				};
			};

			//Left Bottom
			node2: {
				hostname = "ip.add.res.s02";
				port = 2000;
				left-bottomleft: {
					device = 0;
					center = [ -1.7399, 0.7747, 0.86995];
					yaw = -90;
					offset = [0, 0];
					position = [0, 0];
					enabled = true;
					disableMouse = true;
				};
				left-bottomright: {
					device = 1;
					center = [ -1.7399, 0.7747, -0.86995];
					yaw = -90;
					offset = [0, 0];
					position = [2160, 0];
					enabled = true;
					disableMouse = true;
				};
			};

			// Center Top
			node3: {
				hostname = "ip.add.res.s03";
				port = 2000;
				center-topleft: {
					device = 0;
					center = [ -0.86995, 2.3241, -1.7399];
					yaw = 0;
					offset = [0, 0];
					position = [0, 0];
					enabled = true;
					disableMouse = true;
				};
				center-topright:	{
					device = 1;
					center = [ 0.86995, 2.3241, -1.7399];
					yaw = 0;
					offset = [384, 0];
					position = [2160], 0];
					enabled = true;
					disableMouse = true;
				};
			};

			//Center Bottom
			node4: {
				hostname = "ip.add.res.s04";
				port = 2000;
				center-bottomleft: {
					device = 0;
					center = [ -0.86995, 0.7747, -1.7399];
					yaw = 0;
					offset = [0, 0];
					position = [0, 0];
					enabled = true;
					disableMouse = true;
				};
				center-bottomright: {
					device = 1;
					center = [ 0.86995, 0.7747, -1.7399];
					yaw = 0;
					offset = [0, 0];
					position = [2160, 0];
					enabled = true;
					disableMouse = true;
				};
			};


			// Right Top
			node5: {
				hostname = "ip.add.res.s05";
				port = 2000;
				right-topleft: {
					device = 0;
					center = [ 1.7399, 2.3241, -0.86995];
					yaw = 90;
					offset = [0, 320];
					position = [0, 0];
					enabled = true;
					disableMouse = true;
				};
				right-topright: {
					device = 1;
					center = [ 1.7399, 2.3241, 0.86995];
					yaw = 90;
					offset = [0, 320];
					position = [2160, 0];
					enabled = true;
					disableMouse = true;
				};
			};

			// Right Bottom
			node6: {
				hostname = "ip.add.res.s06";
				port = 2000;
				right-bottomleft: {
					device = 0;
					center = [ 1.7399, 0.7747, -0.86995];
					yaw = 90;
					offset = [0, 0];
					position = [0, 0];
					enabled = true;
					disableMouse = true;
				};
				right-bottomright: {
					device = 1;
					center = [ 1.7399, 0.7747, 0.86995];
					yaw = 90;
					offset = [0, 0];
					position = [2160, 0];
					enabled = true;
					disableMouse = true;
				};
			};
		};
	};
	
	input: {
		MouseService: {};
        KeyboardService: {};
	};
	
	console: {
		font: 	{
			filename = "fonts/segoeuimod.ttf";
			size = 18;
		};
	};
	
	defaultFont: {
		filename = "fonts/segoeuimod.ttf";
		size = 24;
	};
	
	camera: {
		controller ="KeyboardMouse";
		headOffset = [ 0.0,  2.0,  0.0 ];
	};
	
	interactor: {
		style = "Mouse";
	};
	
	ui: {
		gamepadInteractionEnabled = true;
		pointerInteractionEnabled = true;
		menu3dEnabled =true;
		menuRayPlaceEnabled = true;
		menuDefaultPosition = [-0.98, 0.2, 1.0];
		menuDefaultScale = 2.5;
		menuToggleButton = "Button3"; 
		clickButton="Button1";
		confirmButton="Button4";
		cancelButton="Button5"; 
	};

	pythonShellEnabled = true;
	drawPointers = true;
	
	missionControl: {
		serverEnabled = true;
		clientEnabled = false;
	};
	
	appDrawer: {
		appDrawerToggleButton="Button7";
	};
};

**Comment by febret** [comment]
What are the tiles that should be on the floor/ceiling? I don't see any tile with pitch specified.

**Comment by bk5115545** [comment]
Sorry about that.  It seems as though I lost an entire node when taking
large comments out.
// Floor
            node7: {
                hostname = "ip.add.res.s07";
                port = 2000;
                floor-top: {
                    device = 0;
                    center = [ 1.7399, 0, -0.86995];
                    yaw = 0;
                    pitch = 90;
                    offset = [0, 0];
                    position = [0, 0];
                    enabled = true;
                    disableMouse = true;
                };
                floor-bottom: {
                    device = 1;
                    center = [ 1.7399, 0, 0.86995];
                    yaw = 0;
                    pitch = 90;
                    offset = [0, 0];
                    position = [2160, 0];
                    enabled = true;
                    disableMouse = true;
                };
            };

On Thu, Nov 5, 2015 at 11:14 AM, Alessandro Febretti <
notifications@github.com> wrote:

> What are the tiles that should be on the floor/ceiling? I don't see any
> tile with pitch specified.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uic-evl/omegalib/issues/160#issuecomment-154126091>.
>



-- 
Blaise Koch
Undergraduate Virtual Reality Researcher
University of Arkansas at Little Rock - Emerging Analytics Center
bbkoch@ualr.edu

**Comment by febret** [comment]
Hi, just wanted to confirm that I'm looking into this. There definitely seem to be an issue with custom configs in general, and isn't just tied to the Equalizer display system.

Tile corners are computed correctly by the config generator when you specify a tile pitch, so I think the error is in the DrawContext transform or viewport computation (https://github.com/uic-evl/omegalib/blob/master/src/omega/DrawContext.cpp#L521).

I'll keep you updated.

**Comment by febret** [comment]
After double checking and testing, it looks like the projection code is fine. I believe the main problem in your case is that pitch angles were inverted so you needed to enter negative values in the config file (-90 instead of 90). I pushed a small update that fixes that. Let me know if it works.

**Comment by febret** [comment]
Also, note that the floor and bottom tiles need to be rotate differently, ie pitch=90 for the floor tile, pitch=-90 for the top tile.

**Comment by febret** [comment]
I will close this issue for now, if this is not solved please reopen.
