### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by morrysa7** [uic-evl/omegalib#163]
Hi..

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

I am trying to make the files but I get this error!

morry@morry-W2600CR:~/Documents/osgART/omega/omegalib$ cmake CMakeLists.txt 
CMAKE_SYSTEM_PROCESSOR: x86_64
Omegalib version identified: 10.2 - master
-- Found GNU readline: /usr/lib/x86_64-linux-gnu/libreadline.so
-- [download 14% complete]
-- [download 38% complete]
-- [download 62% complete]
-- [download 85% complete]
-- [download 100% complete]
-- Configuring done
-- Generating done
-- Build files have been written to: /home/morry/Documents/osgART/omega/omegalib
morry@morry-W2600CR:~/Documents/osgART/omega/omegalib$ sudo make
[  2%] Built target omicron
[ 62%] Built target FreeImage
[ 68%] Built target freetype
[ 75%] Built target ftgl
[ 75%] Built target glew
[ 76%] Building CXX object src/omega/CMakeFiles/omega.dir/Camera.cpp.o
In file included from /home/morry/Documents/osgART/omega/omegalib/include/omega/ApplicationBase.h:42:0,
                 from /home/morry/Documents/osgART/omega/omegalib/include/omega/Texture.h:39,
                 from /home/morry/Documents/osgART/omega/omegalib/include/omega/RenderTarget.h:39,
                 from /home/morry/Documents/osgART/omega/omegalib/src/omega/Camera.cpp:39:
/home/morry/Documents/osgART/omega/omegalib/include/omega/DrawContext.h: In member function ‘omicron::Ref<T>& omega::GpuRef<T>::operator()(const omega::GpuContext&)’:
/home/morry/Documents/osgART/omega/omegalib/include/omega/DrawContext.h:187:44: error: no matching function for call to ‘omega::GpuContext::getId() const’
             return myObjects[context.getId()];
                                            ^
/home/morry/Documents/osgART/omega/omegalib/include/omega/DrawContext.h:187:44: note: candidate is:
In file included from /home/morry/Documents/osgART/omega/omegalib/include/omega/ApplicationBase.h:41:0,
                 from /home/morry/Documents/osgART/omega/omegalib/include/omega/Texture.h:39,
                 from /home/morry/Documents/osgART/omega/omegalib/include/omega/RenderTarget.h:39,
                 from /home/morry/Documents/osgART/omega/omegalib/src/omega/Camera.cpp:39:
/home/morry/Documents/osgART/omega/omegalib/include/omega/GpuResource.h:97:14: note: uint omega::GpuContext::getId() <near match>
         uint getId() { return myId; }
              ^
/home/morry/Documents/osgART/omega/omegalib/include/omega/GpuResource.h:97:14: note:   no known conversion for implicit ‘this’ parameter from ‘const omega::GpuContext*’ to ‘omega::GpuContext*’
In file included from /home/morry/Documents/osgART/omega/omegalib/include/omega/ApplicationBase.h:42:0,
                 from /home/morry/Documents/osgART/omega/omegalib/include/omega/Texture.h:39,
                 from /home/morry/Documents/osgART/omega/omegalib/include/omega/RenderTarget.h:39,
                 from /home/morry/Documents/osgART/omega/omegalib/src/omega/Camera.cpp:39:
/home/morry/Documents/osgART/omega/omegalib/include/omega/DrawContext.h: In member function ‘double& omega::GpuRef<T>::stamp(const omega::GpuContext&)’:
/home/morry/Documents/osgART/omega/omegalib/include/omega/DrawContext.h:195:43: error: no matching function for call to ‘omega::GpuContext::getId() const’
             return myStamps[context.getId()];
                                           ^
/home/morry/Documents/osgART/omega/omegalib/include/omega/DrawContext.h:195:43: note: candidate is:
In file included from /home/morry/Documents/osgART/omega/omegalib/include/omega/ApplicationBase.h:41:0,
                 from /home/morry/Documents/osgART/omega/omegalib/include/omega/Texture.h:39,
                 from /home/morry/Documents/osgART/omega/omegalib/include/omega/RenderTarget.h:39,
                 from /home/morry/Documents/osgART/omega/omegalib/src/omega/Camera.cpp:39:
/home/morry/Documents/osgART/omega/omegalib/include/omega/GpuResource.h:97:14: note: uint omega::GpuContext::getId() <near match>
         uint getId() { return myId; }
              ^
/home/morry/Documents/osgART/omega/omegalib/include/omega/GpuResource.h:97:14: note:   no known conversion for implicit ‘this’ parameter from ‘const omega::GpuContext*’ to ‘omega::GpuContext*’
make[2]: *** [src/omega/CMakeFiles/omega.dir/Camera.cpp.o] Error 1
make[1]: *** [src/omega/CMakeFiles/omega.dir/all] Error 2
make: *** [all] Error 2

Thanks

**Comment by febret** [comment]
Hello, another person reported a similar error. We are investigating.

**Comment by febret** [comment]
I just pushed a fix that should solve this.
By the way, I notice you are checking out the repository manually and doing a build in-source. While this is possible and should work, we **strongly suggest** using the omegalib maintenance scripts to build, configuration and optional module download:

See here: https://github.com/uic-evl/omegalib/blob/master/README.md#if-you-are-in-a-rush (section on the quikc build scripts)
And check this page for more information on the scripts: https://github.com/uic-evl/omegalib/wiki/MaintenanceTools

**Comment by morrysa7** [comment]
Hi,

Thanks a lot... It's working!

**Comment by febret** [comment]
:+1:
