### ISSUE TITLE
osgEarth fails to build

### ISSUE THREAD

**Issue by voidcycles** [uic-evl/omegalib#168]
Building omegaOsgEarth from master fails in several places.

The build errors out trying to compile KmlLoader.cpp which includes a non-existant osgEarth header file since osgEarth hasn't been downloaded or extracted.

The root of the problem is actually the GDAL dependency, which fails to compile HDF5 due to a string expansion included quotes for the build type (eg "Release" is generated instead of Release).  However, the build continues up until the KmlLoader.cpp fails to compile since no error is caught when HDF5 fails to build.

In order to get things to compile I had to manually edit and remove the quotes from the HDF5 config header source code, and in the HDF5 cmake install files.

On CentOS Linux EL 7.  Built using the 'omega' script from git:

./omega build master official-modules

Please fix me!  Thanks!!!

**Comment by febret** [comment]
Thank you for the report, I'm running a fresh build on one of our CentOS 6 systems. Looking at the external project setups for HDF5 here https://github.com/omega-hub/omegaOsgEarth/blob/master/external/UseGDAL.cmake#L53 it seems the configuration type is passed correctly (without quotes). But there might be something else wrong. I will keep you updated (likely tomorrow, it's night here :zzz:)

**Comment by febret** [comment]
This should be fixed. To make sure you get the fix you will need to delete the cmake script in your omegalib directory (the dir where you downloaded the omega build script:
```
> rm -rf cmake
> rm -rf master
> ./omega get master omegaOsgEarth
```
