### ISSUE TITLE
oculus module requires external SDK

### ISSUE THREAD

**Issue by voidcycles** [uic-evl/omegalib#169]
The 'oculus' module is included in the 'official-modules' list, but it requires additional dependencies.

I might suggest either including the SDK download in the CMake build, or move the oculus module outside of the official modules list since it can't be built out of the box.

**Comment by febret** [comment]
Hi,
the official module is for packaging binary distributions, it's basically setup for running automated builds on OSX & Windows where the required packages for distribution (ie oculus) are installed on the build machine.

If you are on linux, my suggestion is to use the 'common-modules' bundle, or downloading the packages you want explicitly.

To disable oculus on your build do 
`./omega set master MODULES_oculus False`

You can also `rm -rf master/modules/oculus` afterwards if you want to get rid of the code.
