### ISSUE TITLE
mvi fails to build against master

### ISSUE THREAD

**Issue by voidcycles** [uic-evl/omegalib#170]
It appears the include statements are out of date:

OmegaLib/master/modules/mvi/AppController.cpp:1:32: fatal error: omega/MouseService.h: No such file or directory
#include <omega/MouseService.h>

**Comment by febret** [comment]
The mvi module online is very much out of date and quite experimental. It's stuff from my PhD. I wouldn't download it unless you really want to use it for a specific reason :)

**Comment by febret** [comment]
To clarify: I plan to upload a working version soon, either in that module or a separate 'final' one. A lot of the code in mvi in its current form is the result of a lot of experiments. Lots of streamlining to do.
