### ISSUE TITLE
Add docs and diagrams for display geometry

### ISSUE THREAD

**Issue by voidcycles** [uic-evl/omegalib#171]
Could you please provide a description of the coordinate space mapping and viewport definitions for the display geometry types?  In particular cylindrical and planar mappings for multinode clusters?

The examples are functional, but I'd rather not spend days trying to work out the correct mapping for our setup.

Thanks!!

**Comment by febret** [comment]
If you give me some details on your setup I can integrate the docs

**Comment by voidcycles** [comment]
It would be extremely helpful to have a diagram showing how the viewport coordinate system is defined in relation to the geometry and arrangement of tiles.  In particular, cylindrical and planar multinode systems.  For example, given a 6x node 170 degree cylinder display with 6x tiles generating top/bottom stereo pairs at 1920x1200 resolution ...

**Comment by febret** [comment]
https://github.com/uic-evl/omegalib/wiki/ConfigReference

added a diagram and links to a couple of examples configurations for planar & cylindrical displays
