### ISSUE TITLE
reconfiguring Cmake caches generate by mtools removes the modules.

### ISSUE THREAD

**Issue by koosha94** [uic-evl/omegalib#177]
Observed in OSX ( while using either makefiles or Xcode).
Reconfiguring the cmake cache removes the added modules from building.
Moduels are addded again by simply disabling one of the added modules( under modules tab in cmake window)

**Comment by febret** [comment]
FYI, I reworked the master branch implementation of module support to remove the need for a 'hub' repository. It would be good to see if this problem still exists after you pull the latest changes..
