### ISSUE TITLE
Update omegalib.io from the repository

### ISSUE THREAD

**Issue by koosha94** [uic-evl/omegalib#178]
mtools/get.cmake is modifed to support xcode builds,
update the hosted version accordingly.

**Comment by febret** [comment]
Builds always use the version in mtools directly, so no need to update. See https://github.com/uic-evl/omegalib/blob/gh-pages/omega.cmake#L112

**Comment by koosha94** [comment]
unfortunately for the get function they don't use the repositiory version and fetch this file:
https://uic-evl.github.io/omegalib/omega.cmake

**Comment by febret** [comment]
You are right. I removed mtools/get.cmake and added your change directly to omega.cmake
